version: 2.1

parameters:
  # These pipeline parameters are required by the
  # "trigger-integration-tests-workflow" job
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:int-testing"

orbs:
  mdp: hubci/md-proofer@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@9.1

workflows:
  lint_pack-validate_publish-dev:  # runs on every commit
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          # release dev version of orb, for testing & possible publishing.
          # orb will be published as <<pipeline.dev-orb-version>> and dev:${CIRCLE_SHA1:0:7}.
          orb-name: hubci/md-proofer
          checkout: true
          orb-path: orb.yml
          alpha-version-ref: dev:int-testing
          validate: true
          requires:
            - orb-tools/lint
          context: orbs
      - orb-tools/trigger-integration-tests-workflow:
          # trigger an integration workflow to test the
          # dev:${CIRCLE_SHA1:0:7} version of your orb
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
          context: orbs
  integration-tests_prod-release:
    # This `integration-tests_prod-release` workflow will only run
    # when the run-integration-tests pipeline parameter is set to true.
    # It is meant to be triggered by the "trigger-integration-tests-workflow"
    # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1

      # publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: hubci/md-proofer
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - integration-test-1
          filters:
            branches:
              only: master
          context: orbs

jobs:
  integration-test-1:
    docker:
      - image: cimg/base:2020.05
    steps:
      - mdp/install:
          version: "0.3.0"
      - run:
          name: "Try running Markdown Proofer"
          command: md-proofer version
